-- 切片策略选择（指南 §3/42）：AUTO 由系统按文件类型路由，其余为显式策略

ALTER TABLE `knowledge_base`
    ADD COLUMN `chunk_strategy` varchar(32) NOT NULL DEFAULT 'AUTO'
        COMMENT 'FIXED_SIZE/RECURSIVE/PARAGRAPH/SENTENCE/SEMANTIC/STRUCTURE/MARKDOWN/HTML/PDF_LAYOUT/TABLE/QA/PARENT_CHILD/SLIDING_WINDOW/CODE/AUTO'
        AFTER `child_overlap`;
